### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by levinhne** [hhatto/nude.py#13]
Traceback (most recent call last):
  File "/usr/local/bin/nudepy", line 9, in <module>
    load_entry_point('nudepy==0.2', 'console_scripts', 'nudepy')()
  File "/usr/local/lib/python2.7/dist-packages/nudepy-0.2-py2.7.egg/nude.py", line 438, in main
    callback(_testfile(fname, resize=args.resize))
  File "/usr/local/lib/python2.7/dist-packages/nudepy-0.2-py2.7.egg/nude.py", line 373, in _testfile
    n.parse()
  File "/usr/local/lib/python2.7/dist-packages/nudepy-0.2-py2.7.egg/nude.py", line 89, in parse
    pixels = self.image.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 203, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 420, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder zip not available

**Comment by Blucknote** [comment]
Try this one https://stackoverflow.com/a/12359864/10001426
may be you need other libraries
